### PR TITLE
Recognize OP_66 as manually cursed and inscription is bound

### PR DESCRIPTION
**Pull request by dannydeezy**
This would clean up the mess that us degens made

### CODE REVIEW

**Comment by SmarakNayak** [comment]
Would appreciate OP_66 recognition as well!

**Comment by casey** [comment]
See https://github.com/casey/ord/pull/2109#issuecomment-1562326574.

**Comment by dannydeezy** [comment]
Made a discussion in ord for OP_66 https://github.com/casey/ord/discussions/2113

**Comment by BatBushRacks** [comment]
@casey @raphjaph @veryordinally please say something on this or the other idea from @dannydeezy... not just a lame fiat decision... engage and participate... stop the hiding... makes no sense... people want to work together... people want inscriptions bound... so why not work with them and have more open source devs helping out? https://github.com/ordinals/ord/pull/2145

**Pull request closed without merging**
